export const exertion = [{
    "Squat": {
        1: [
            {muscle: "Biceps", value: 1},
            {muscle: "Latissimus Dorsi", value: 2},
            {muscle: "Erector Spinae", value: 2},
            {muscle: "Trapezius", value: 4},
            {muscle: "Deltoids", value: 2},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 5},
            {muscle: "Glutes", value: 4},
            {muscle: "Quadriceps", value: 4},
            {muscle: "Hamstrings", value: 4},
            {muscle: "Calves", value: 5}
        ],
        2: [
            {muscle: "Biceps", value: 1},
            {muscle: "Latissimus Dorsi", value: 3},
            {muscle: "Erector Spinae", value: 4},
            {muscle: "Trapezius", value: 4},
            {muscle: "Deltoids", value: 2},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 7},
            {muscle: "Glutes", value: 5},
            {muscle: "Quadriceps", value: 5},
            {muscle: "Hamstrings", value: 6},
            {muscle: "Calves", value: 6}
        ],
        3: [
            {muscle: "Biceps", value:1},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 6},
            {muscle: "Trapezius", value: 4},
            {muscle: "Deltoids", value: 2},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 7},
            {muscle: "Glutes", value: 6},
            {muscle: "Quadriceps", value: 7},
            {muscle: "Hamstrings", value: 7},
            {muscle: "Calves", value: 6}
        ],
        4: [
            {muscle: "Biceps", value:1},
            {muscle: "Latissimus Dorsi", value: 6},
            {muscle: "Erector Spinae", value: 9},
            {muscle: "Trapezius", value: 5},
            {muscle: "Deltoids", value: 2},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 2},
            {muscle: "Abdominals", value: 10},
            {muscle: "Glutes", value: 9},
            {muscle: "Quadriceps", value: 10},
            {muscle: "Hamstrings", value: 9},
            {muscle: "Calves", value: 8}
        ],
        5: [
            {muscle: "Biceps", value:1},
            {muscle: "Latissimus Dorsi", value: 6},
            {muscle: "Erector Spinae", value: 10},
            {muscle: "Trapezius", value: 5},
            {muscle: "Deltoids", value: 3},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 10},
            {muscle: "Glutes", value: 10},
            {muscle: "Quadriceps", value: 10},
            {muscle: "Hamstrings", value: 9},
            {muscle: "Calves", value: 8}
        ],
        6: [
            {muscle: "Biceps", value:1},
            {muscle: "Latissimus Dorsi", value: 5},
            {muscle: "Erector Spinae", value: 8},
            {muscle: "Trapezius", value: 4},
            {muscle: "Deltoids", value: 2},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 8},
            {muscle: "Glutes", value: 9},
            {muscle: "Quadriceps", value: 9},
            {muscle: "Hamstrings", value: 7},
            {muscle: "Calves", value: 6}
        ],
        7: [
            {muscle: "Biceps", value:1},
            {muscle: "Latissimus Dorsi", value: 2},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 4},
            {muscle: "Deltoids", value: 2},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 5},
            {muscle: "Glutes", value: 6},
            {muscle: "Quadriceps", value: 5},
            {muscle: "Hamstrings", value: 5},
            {muscle: "Calves", value: 5}
        ],
    },
    "Bench": {
        1: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 3},
            {muscle: "Triceps", value: 4},
            {muscle: "Pectorals", value: 4},
            {muscle: "Abdominals", value: 2},
            {muscle: "Glutes", value: 1},
            {muscle: "Quadriceps", value: 1},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 1}
        ],
        2: [
            {muscle: "Biceps", value:2},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 3},
            {muscle: "Triceps", value: 5},
            {muscle: "Pectorals", value: 5},
            {muscle: "Abdominals", value: 2},
            {muscle: "Glutes", value: 1},
            {muscle: "Quadriceps", value: 1},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 1}
        ],
        3: [
            {muscle: "Biceps", value:2},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 4},
            {muscle: "Triceps", value: 7},
            {muscle: "Pectorals", value: 7},
            {muscle: "Abdominals", value: 2},
            {muscle: "Glutes", value: 1},
            {muscle: "Quadriceps", value: 1},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 1}
        ],
        4: [
            {muscle: "Biceps", value: 2},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 6},
            {muscle: "Triceps", value: 10},
            {muscle: "Pectorals", value: 9},
            {muscle: "Abdominals", value: 4},
            {muscle: "Glutes", value: 2},
            {muscle: "Quadriceps", value: 3},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 3}
        ],
        5: [
            {muscle: "Biceps", value:2},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 6},
            {muscle: "Triceps", value: 10},
            {muscle: "Pectorals", value: 10},
            {muscle: "Abdominals", value: 2},
            {muscle: "Glutes", value: 1},
            {muscle: "Quadriceps", value: 1},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 1}
        ],
        6: [
            {muscle: "Biceps", value:2},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 5},
            {muscle: "Triceps", value: 8},
            {muscle: "Pectorals", value: 8},
            {muscle: "Abdominals", value: 2},
            {muscle: "Glutes", value: 1},
            {muscle: "Quadriceps", value: 1},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 1}
        ],
        7: [
            {muscle: "Biceps", value:2},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 4},
            {muscle: "Triceps", value: 7},
            {muscle: "Pectorals", value: 6},
            {muscle: "Abdominals", value: 2},
            {muscle: "Glutes", value: 1},
            {muscle: "Quadriceps", value: 1},
            {muscle: "Hamstrings", value: 1},
            {muscle: "Calves", value: 1}
        ],
    },
    "Deadlift": {
        1: [
            {muscle: "Biceps", value:1},
            {muscle: "Latissimus Dorsi", value: 4},
            {muscle: "Erector Spinae", value: 3},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 4},
            {muscle: "Glutes", value: 3},
            {muscle: "Quadriceps", value: 4},
            {muscle: "Hamstrings", value: 3},
            {muscle: "Calves", value: 3}
        ],
        2: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 6},
            {muscle: "Erector Spinae", value: 10},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 6},
            {muscle: "Glutes", value: 8},
            {muscle: "Quadriceps", value: 10},
            {muscle: "Hamstrings", value: 7},
            {muscle: "Calves", value: 6}
        ],
        3: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 6},
            {muscle: "Erector Spinae", value: 10},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 9},
            {muscle: "Glutes", value: 8},
            {muscle: "Quadriceps", value: 10},
            {muscle: "Hamstrings", value: 8},
            {muscle: "Calves", value: 6}
        ],
        4: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 7},
            {muscle: "Erector Spinae", value: 10},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 9},
            {muscle: "Glutes", value: 10},
            {muscle: "Quadriceps", value: 8},
            {muscle: "Hamstrings", value: 9},
            {muscle: "Calves", value: 4}
        ],
        5: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 8},
            {muscle: "Erector Spinae", value: 7},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 6},
            {muscle: "Glutes", value: 10},
            {muscle: "Quadriceps", value: 7},
            {muscle: "Hamstrings", value: 7},
            {muscle: "Calves", value: 4}
        ],
        6: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 8},
            {muscle: "Erector Spinae", value: 5},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 5},
            {muscle: "Glutes", value: 8},
            {muscle: "Quadriceps", value: 6},
            {muscle: "Hamstrings", value: 7},
            {muscle: "Calves", value: 4}
        ],
        7: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 7},
            {muscle: "Erector Spinae", value: 5},
            {muscle: "Trapezius", value: 2},
            {muscle: "Deltoids", value: 1},
            {muscle: "Triceps", value: 2},
            {muscle: "Pectorals", value: 1},
            {muscle: "Abdominals", value: 5},
            {muscle: "Glutes", value: 6},
            {muscle: "Quadriceps", value: 6},
            {muscle: "Hamstrings", value: 6},
            {muscle: "Calves", value: 4}
        ],
    }
}]