export const exertion = [{
    "Squat": {
        1: [
            {muscle: "Biceps", value: 0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 1},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        2: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 2},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        3: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        4: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        5: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        6: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        7: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
    },
    "Bench": {
        1: [
            {muscle: "Biceps", value:3},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        2: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        3: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        4: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        5: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        6: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        7: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
    },
    "Deadlift": {
        1: [
            {muscle: "Biceps", value:4},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        2: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        3: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        4: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        5: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        6: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
        7: [
            {muscle: "Biceps", value:0},
            {muscle: "Latissimus Dorsi", value: 0},
            {muscle: "Erector Spinae", value: 0},
            {muscle: "Trapezius", value: 0},
            {muscle: "Deltoids", value: 0},
            {muscle: "Triceps", value: 0},
            {muscle: "Pectorals", value: 0},
            {muscle: "Abdominals", value: 0},
            {muscle: "Glutes", value: 0},
            {muscle: "Quadriceps", value: 0},
            {muscle: "Hamstrings", value: 0},
            {muscle: "Calves", value: 0}
        ],
    }
}]