exertion = [
    {
        "Squat": {
            1: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            2: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            3: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            4: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            5: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            6: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            7: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            }
        },
        "Bench Press": {
            1: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            2: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            3: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            4: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            5: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            6: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            7: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            }
        },
        "Deadlift": {
            1: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            2: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            3: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            4: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            5: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            6: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            },
            7: {
                "Biceps": 0,
                "Latissimus Dorsi": 0,
                "Erector Spinae": 0,
                "Trapezius": 0,
                "Deltoids": 0,
                "Triceps": 0,
                "Pectorals": 0,
                "Abdominals": 0,
                "Glutes": 0,
                "Quadriceps": 0,
                "Hamstrings": 0,
                "Calves": 0
            }
        }
    }
]